from gi.repository import Gtk

from lib_sallybn import MainWindowHandler
# FIXME Not here
import lib_sallybn.util.resources as res


class SallyApp(Gtk.Application):
    def __init__(self):
        Gtk.Application.__init__(self)

    def do_startup(self):
        print "startup"
        Gtk.Application.do_startup(self)

    def do_activate(self):
        # Set the Glade file
        builder = Gtk.Builder()
        builder.add_from_file(res.MAIN_WINDOW_GLADE)

        #Get the Main Window, and connect the "destroy" event
        window = builder.get_object("MainWindow")
        window.set_size_request(800, 600)
        window.set_application(self)


        #notebook_main
        tabber = builder.get_object("notebook_main")
        tabber.remove_page(0)

        # Handler for signals generated by main window
        handler = MainWindowHandler.MainWindowHandler(window, tabber)
        builder.connect_signals(handler)

        window.connect("delete-event", Gtk.main_quit)
        window.connect("destroy", Gtk.main_quit)

        # window.show_all()




